# server config
server:
  port: 10000

# Allow Thymeleaf templates to be reloaded at dev time
spring:
  thymeleaf.cache: false
  application:
    name: asion-search-server
  datasource:
    url: jdbc:mysql://192.168.99.100:1006/asion_search_sample?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: asion
    driverClassName: com.mysql.jdbc.Driver
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    max-wait: 30000
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 20000
    min-evictable-idle-time-millis: 28700

logging:
  level:
    root: info
  file: asion-search-server.log