# server config
server:
  port: 9980

management:
  server:
    port: 9981

# Allow Thymeleaf templates to be reloaded at dev time
spring:
  thymeleaf.cache: false
#  mvc.favicon.enabled: false
  application:
    name: asion-webflux-web
  resources:
    static-locations: "classpath:/META-INF/resources/webjars/"
  dubbo:
    app: asion-webflux-web
    registry: redis://dubbo.asion.org:5050
    protocol: dubbo

  boot:
      admin:
        client:
          instance:
            management-url: http://boot.admin.asion.org:10090
  servlet:
    multipart:
      max-file-size: 2Mb
      max-request-size: 10Mb

logging:
  level:
    root: info
  file: asion-webflux-web.log