@startuml

title 两阶段提交成功时序图

协调者 -> 参与者1: 准备
note right
写redo、undo日志、
锁定资源、执行操作、不提交
end note
协调者 <- 参与者1: 准备成功

协调者 -> 参与者2: 准备
note right
写redo、undo日志、
锁定资源、执行操作、不提交
end note
协调者 <- 参与者2: 准备成功

协调者 -> 参与者1: 提交
note right: 提交操作、释放资源
协调者 <- 参与者1: 提交成功

协调者 -> 参与者2: 提交
note right: 提交操作、释放资源
协调者 <- 参与者2: 提交成功

@enduml