@startuml

title 三阶段提交成功时序图

协调者 -> 参与者1: 询问
note left
校验，超时导致终止
end note
协调者 <- 参与者1: 可以执行

协调者 -> 参与者2: 询问
note left
校验，超时导致终止
end note
协调者 <- 参与者2: 可以执行

协调者 -> 参与者1: 准备
note right
写redo、undo日志、
锁定资源、执行操作、
超时导致成功
end note
协调者 <- 参与者1: 准备成功

协调者 -> 参与者2: 准备
note right
写redo、undo日志、
锁定资源、执行操作、
超时导致成功
end note
协调者 <- 参与者2: 准备成功

协调者 -> 参与者1: 提交
note left: 提交操作、释放资源
协调者 <- 参与者1: 提交成功

协调者 -> 参与者2: 提交
note left: 提交操作、释放资源
协调者 <- 参与者2: 提交成功

@enduml