#network.bind_host: 0.0.0.0
network.host: 0.0.0.0
cluster.name: elasticsearch_cluster
node.name: es-node-2a
#node.master: false
#node.data: true
#http.cors.enabled: true
#http.cors.allow-origin: "*"

discovery.zen.minimum_master_nodes: 1
discovery.zen.ping.unicast.hosts: es.asion.io