
// create
POST http://{{host}}:{{port}}/accounts
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "id": 1001,
  "code": "testcode2",
  "username": "test2",
  "password": "test2"
}

### page list

GET http://{{host}}:{{port}}/accounts?pageNum=1&pageSize=10
Accept: application/json

### get by id

GET http://{{host}}:{{port}}/accounts/{{accountId}}
Accept: application/json

### update by id

PUT http://{{host}}:{{port}}/accounts/{{accountId}}
Content-Type: application/json

{
  "id": 1000,
  "code": "testcode1",
  "username": "test1",
  "password": "password1",
  "nickName": null,
  "usedPassword": "test1",
  "mobile": "15333992199",
  "email": "vincent@seekheap.com",
  "weChatId": "HsianLu",
  "enabled": true
}

### disable by id

DELETE http://{{host}}:{{port}}/accounts/{{accountId}}
Accept: application/json

### register

GET http://{{host}}:{{port}}/register/15339992199
Accept: application/json

### captcha

GET http://{{host}}:{{port}}/captcha
Content-Type: image/jpeg

### validate

POST http://{{host}}:{{port}}/captcha/validate?captcha=np4n
Set-Cookie: cid=6cedf285-74b1-4f18-a9b3-15a30934d0e3; Max-Age=180; Expires=Wed, 09-Jan-2019 04:21:31 GMT; Domain=localhost; Path=/

###