# server config
server:
  port: 9909

# Allow Thymeleaf templates to be reloaded at dev time
spring:
  thymeleaf.cache: false
  application:
    name: asion-account-server
  datasource:
    url: jdbc:mysql://db.asion.org:2006/asion_account?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: asion
    driverClassName: com.mysql.jdbc.Driver
#  dubbo:
#    app: dubbo-account-provider
#    registry: redis://dubbo.asion.org:5050
#    protocol: dubbo
#    port: 9908
#  boot:
#    admin:
#      client:
#        instance:
#          management-url: http://boot.admin.asion.org:10090
#
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml

# Base packages to scan Dubbo Components (e.g., @Service, @Reference)
dubbo.scan.basePackages: io.vincent.account.domain.application

# Dubbo Config properties
## ApplicationConfig Bean
dubbo.application.id: dubbo-provider-account
dubbo.application.name: dubbo-provider-account

## ProtocolConfig Bean
dubbo.protocol.id: dubbo
dubbo.protocol.name: dubbo
dubbo.protocol.port: 2008

## RegistryConfig Bean
dubbo.registry.id: dubbo-account-provider
dubbo.registry.address: redis://dubbo.asion.org:5050

# logger
logging:
  level:
    root: info
  file: asion-account-server.log

# eureka
#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://eureka.asion.org:8761/eureka/
