# server config
server:
  port: 9909

# Allow Thymeleaf templates to be reloaded at dev time
spring:
  thymeleaf.cache: false
  application:
    name: asion-sample-server
  datasource:
    url: jdbc:mysql://192.168.99.100:2006/asion_sample?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: asion
    driverClassName: com.mysql.jdbc.Driver
    dbcp:
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      max-wait: 30000
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 20000
      min-evictable-idle-time-millis: 28700

  dubbo:
    app: dubbo-account-provider
    registry: redis://dubbo.asion.org:5050
    protocol: dubbo
    port: 9908

logging:
  level:
    root: info
  file: asion-sample-server.log