# server config
server:
  port: 9980

#management:
#  server:
#    port: 9981

# Allow Thymeleaf templates to be reloaded at dev time
spring:
  thymeleaf.cache: false
#  mvc.favicon.enabled: false
  application:
    name: asion-account-web
#  dubbo:
#    app: asion-account-web
#    registry: redis://dubbo.asion.org:5050
#    protocol: dubbo
#  boot:
#      admin:
#        url: http://boot.admin.asion.org:10090
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
  # spring security
#  security:
#    user:
#      roles: USER, OPERATOR
#      name: user
#      password: 123456

  # Normal redis config.
  redis:
    host: dubbo.asion.org
    port: 5050

# Base packages to scan Dubbo Components (e.g., @Service, @Reference)
#dubbo.scan.basePackages: io.vincent.account

# Dubbo Config properties
## ApplicationConfig Bean
dubbo.application.id: dubbo-consumer-account
dubbo.application.name: dubbo-consumer-account

## ProtocolConfig Bean
dubbo.protocol.id: dubbo
dubbo.protocol.name: dubbo
dubbo.protocol.port: 9907

## RegistryConfig Bean
dubbo.registry.id: dubbo-account-provider
dubbo.registry.address: redis://dubbo.asion.org:5050

logging:
  level:
    root: info
  file: asion-account-web.log

## Account config.
account:
  domain: localhost
  captcha:
    need: true
    user-need: false
    mobile-need: true
